### PR TITLE
Update for new Pkg manager and Registry, switch CI

### PR DESCRIPTION
**Pull request by ScottPJones**
Add Project.toml for new Pkg manager
Use GitHub Actions and Drone for CI instead of Travis and Appveyor

### CODE REVIEW

**Comment by ScottPJones** [comment]
@tanmaykm Could you take a look at this, also, could you register these 3 packages? (HPack.jl, HTTP2.jl, and gRPC.jl)?
Thanks!

**Comment by tanmaykm** [comment]
Thanks @ScottPJones . I shall merge this.

But I am not sure if we should register this package. Because this repo is actually a fork from @sorpaas 's https://github.com/sorpaas/HPack.jl. And as mentioned in the README, there was an effort (and still ongoing I believe?) to have this in HTTP.jl. It may be best to for a while.

**Comment by ScottPJones** [comment]
@sorpaas hasn't really done anything with HTTP2.jl and HPack.jl in 4 years (the last modification was actually by Elliot Saba, which got merged 2 years ago, and was related to changing the appveyor.yml file, nothing else).  They seem to be very busy working on blockchain related code.
They might be amenable to moving these packages to another owner (we might like to take them over, at the Humans-of-Julia  organization, where we need this functionality as part of a project to develop a client for the Grakn database software).
I think HTTP2.jl and HPack.jl could be safely registered (after all, with the new registry system with UUIDs, it doesn't prevent other people from even registering packages with the same name).
The functionality of these two would likely not be in separate packages anyway, but would be incorporated into HTTP.jl.

**Comment by tanmaykm** [comment]
Okay. Sounds good. I have added you as collaborator to my fork of HPack.jl, HTTP2.jl and gRPC.jl. Happy to transfer these to any org as well. Please feel free to transfer them to your org and/or register them as you wish. I think doing the transfer before registration will be good. Do let me know if I need to do anything additional for the transfer.

**Comment by aviks** [comment]
I don't think HTTP2.jl is anyway near a state to be registered. For starters, it has a dependency on HTTPCommon, which is a deprecated package. Someone needs to put in the work to rebase it on top of HTTP.jl at the very least, before it can be registered. 

Also, HTTP.jl has an implementation of HPack. HTTP2.jl should probably be rebased on top of that as well. Otherwise, you are left with more unmaintainable packages.

**Comment by ScottPJones** [comment]
> For starters, it has a dependency on HTTPCommon, which is a deprecated package.

@aviks Are you looking at an older version of HTTP2.jl?  It no longer has any dependency on HTTPCommon.

**Pull request merged**
